#include <render/features/SpriteFeature.h>

// Pre-compiled SPIR-V blobs -- generated by the offline build pipeline.
// Each header exposes:
//   inline constexpr uint32_t <VAR>[];
//   inline constexpr uint32_t <VAR>WordCount;
#include <shaders/kSpriteVertSpv.h>
#include <shaders/kSpriteFragSpv.h>

// Pipeline metadata (sprite.shader JSON baked as a constexpr string).
#include <shaders/kSpriteShaderMetadata.h>

#include <render/backend/vulkan/ShaderMetadata.h>
#include <render/backend/vulkan/VulkanBufferService.h>
#include <render/backend/vulkan/VulkanDescriptorCache.h>
#include <render/backend/vulkan/VulkanDeviceService.h>
#include <render/backend/vulkan/VulkanFrameScratch.h>
#include <render/backend/vulkan/VulkanPipelineCache.h>
#include <render/backend/vulkan/VulkanShaderCache.h>

#include <algorithm>
#include <cmath>
#include <cstring>

void SpriteFeature::Setup(const RendererServices& services)
{
    Logging    = services.Logging;
    DeviceService = services.Device;
    Buffers    = services.Buffers;
    Shaders    = services.Shaders;
    Pipelines  = services.Pipelines;
    Descriptors = services.Descriptors;
    Scratch    = services.Scratch;

    if (!Logging || !DeviceService || !Buffers || !Shaders
        || !Pipelines || !Descriptors || !Scratch)
    {
        return;
    }

    Logger& log = Logging->GetLogger<SpriteFeature>();

    // ── Load pre-compiled SPIR-V modules ──────────────────────────────────
    // The arrays are embedded by the build pipeline; no file I/O, no compiler.
    VertexShader = Shaders->CreateModuleFromSpirv(
        kSpriteVertSpv, kSpriteVertSpvWordCount, "sprite.vert");
    FragmentShader = Shaders->CreateModuleFromSpirv(
        kSpriteFragSpv, kSpriteFragSpvWordCount, "sprite.frag");

    if (!VertexShader.IsValid() || !FragmentShader.IsValid())
    {
        log.Error("SpriteFeature: shader module creation failed");
        return;
    }

    // ── Parse pipeline metadata ───────────────────────────────────────────
    // kSpriteShaderMetadata is the embedded sprite.shader JSON.
    // MetaDesc receives everything except shader handles, pipeline layout,
    // vertex attributes, and color formats -- those vary per draw.
    {
        std::string err;
        if (!ParseShaderMetadataToDesc(kSpriteShaderMetadata, MetaDesc, err))
        {
            log.Error("SpriteFeature: failed to parse shader metadata: {}", err);
            return;
        }
    }

    // ── Pipeline layout ───────────────────────────────────────────────────
    PipelineLayout = Descriptors->GetDefaultPipelineLayout();
    if (PipelineLayout == VK_NULL_HANDLE)
    {
        log.Error("SpriteFeature: failed to acquire pipeline layout");
        return;
    }

    // Point set-0 binding-0 at the frame scratch ring.
    // 256 bytes is a conservative cap that covers the FrameUbo for any
    // near-term feature via dynamic offset, and is well under every device's
    // maxUniformBufferRange.
    Descriptors->SetFrameUniformBuffer(Scratch->GetBuffer(), 256);

    Valid = true;
}

void SpriteFeature::Teardown()
{
    if (Shaders)
    {
        if (VertexShader.IsValid())   Shaders->Destroy(VertexShader);
        if (FragmentShader.IsValid()) Shaders->Destroy(FragmentShader);
    }
    VertexShader       = {};
    FragmentShader     = {};
    MetaDesc           = {};
    CachedPipeline     = VK_NULL_HANDLE;
    CachedColorFormat  = VK_FORMAT_UNDEFINED;
    PipelineLayout     = VK_NULL_HANDLE;
    Pending.clear();
    Pending.shrink_to_fit();
    Valid = false;
}

void SpriteFeature::Submit(const Sprite& sprite)
{
    if (!Valid) return;
    Pending.push_back(sprite);
}

void SpriteFeature::ReservePending(size_t count)
{
    Pending.reserve(count);
}

void SpriteFeature::ClearPending()
{
    Pending.clear();
}

bool SpriteFeature::BuildPipeline(VkFormat colorFormat)
{
    if (CachedPipeline != VK_NULL_HANDLE && CachedColorFormat == colorFormat)
        return true;

    // Start from the metadata-driven base state and fill in the
    // per-feature / per-frame fields that the .shader file doesn't own.
    GraphicsPipelineDesc desc = MetaDesc;
    desc.VertexShader  = VertexShader;
    desc.FragmentShader = FragmentShader;
    desc.Layout        = PipelineLayout;
    desc.ColorFormats  = { colorFormat };

    // Vertex attribute array -- describes the exact binary layout of GpuInstance.
    // These are tied to the C++ struct and must be kept in sync with it.
    // Phase 3 (SPIR-V reflection) will validate location / format agreement
    // automatically; for now the static_assert on sizeof(GpuInstance) is the guard.
    auto addAttr = [&](uint32_t loc, VkFormat fmt, uint32_t off)
    {
        VertexInputAttributeDesc a{};
        a.Location = loc;
        a.Binding  = 0;
        a.Format   = fmt;
        a.Offset   = off;
        desc.VertexAttributes.push_back(a);
    };
    addAttr(0, VK_FORMAT_R32G32_SFLOAT, offsetof(GpuInstance, Center));
    addAttr(1, VK_FORMAT_R32G32_SFLOAT, offsetof(GpuInstance, HalfExtents));
    addAttr(2, VK_FORMAT_R32G32_SFLOAT, offsetof(GpuInstance, UvMin));
    addAttr(3, VK_FORMAT_R32G32_SFLOAT, offsetof(GpuInstance, UvMax));
    addAttr(4, VK_FORMAT_R32_UINT,      offsetof(GpuInstance, Color));
    addAttr(5, VK_FORMAT_R32_UINT,      offsetof(GpuInstance, TextureIndex));
    addAttr(6, VK_FORMAT_R32G32_SFLOAT, offsetof(GpuInstance, SinRot));

    VkPipeline pipeline = Pipelines->GetGraphicsPipeline(desc);
    if (pipeline == VK_NULL_HANDLE)
        return false;

    CachedPipeline    = pipeline;
    CachedColorFormat = colorFormat;
    return true;
}

void SpriteFeature::OnDraw(const FrameContext& frame)
{
    if (!Valid) return;
    if (Pending.empty()) return;

    if (!BuildPipeline(frame.TargetFormat))
    {
        Pending.clear();
        return;
    }

    // Stable-sort by SortKey; equal keys preserve submission order.
    std::stable_sort(Pending.begin(), Pending.end(),
        [](const Sprite& a, const Sprite& b) { return a.SortKey < b.SortKey; });

    // Allocate a frame-UBO slot and write InvViewport.
    const VulkanFrameScratch::Allocation uboAlloc =
        Scratch->AllocateUniform(sizeof(FrameUbo));
    if (!uboAlloc.IsValid())
    {
        Pending.clear();
        return;
    }

    FrameUbo ubo{};
    if (frame.TargetExtent.width  > 0)
        ubo.InvViewport[0] = 1.0f / static_cast<float>(frame.TargetExtent.width);
    if (frame.TargetExtent.height > 0)
        ubo.InvViewport[1] = 1.0f / static_cast<float>(frame.TargetExtent.height);
    std::memcpy(uboAlloc.Mapped, &ubo, sizeof(ubo));

    // Allocate the instance vertex buffer.
    const VkDeviceSize instanceBytes =
        sizeof(GpuInstance) * static_cast<VkDeviceSize>(Pending.size());
    const VulkanFrameScratch::Allocation vboAlloc =
        Scratch->AllocateVertex(instanceBytes);
    if (!vboAlloc.IsValid())
    {
        Pending.clear();
        return;
    }

    auto* gpu = static_cast<GpuInstance*>(vboAlloc.Mapped);
    for (size_t i = 0; i < Pending.size(); ++i)
    {
        const Sprite& s = Pending[i];
        GpuInstance&  g = gpu[i];
        g.Center[0]      = s.CenterX;
        g.Center[1]      = s.CenterY;
        g.HalfExtents[0] = s.Width  * 0.5f;
        g.HalfExtents[1] = s.Height * 0.5f;
        g.UvMin[0]       = s.UvMinX;
        g.UvMin[1]       = s.UvMinY;
        g.UvMax[0]       = s.UvMaxX;
        g.UvMax[1]       = s.UvMaxY;
        g.Color          = s.Color;
        g.TextureIndex   = s.Texture.IsValid() ? s.Texture.Value : 0u;
        g.SinRot         = std::sin(s.Rotation);
        g.CosRot         = std::cos(s.Rotation);
    }

    const VkBuffer ringBuffer = Buffers->GetBuffer(vboAlloc.Buffer);
    if (ringBuffer == VK_NULL_HANDLE)
    {
        Pending.clear();
        return;
    }

    vkCmdBindPipeline(frame.Cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, CachedPipeline);

    VkViewport viewport{};
    viewport.x        = 0.0f;
    viewport.y        = 0.0f;
    viewport.width    = static_cast<float>(frame.TargetExtent.width);
    viewport.height   = static_cast<float>(frame.TargetExtent.height);
    viewport.minDepth = 0.0f;
    viewport.maxDepth = 1.0f;
    vkCmdSetViewport(frame.Cmd, 0, 1, &viewport);

    VkRect2D scissor{};
    scissor.offset = { 0, 0 };
    scissor.extent = frame.TargetExtent;
    vkCmdSetScissor(frame.Cmd, 0, 1, &scissor);

    const VkDescriptorSet sets[2] = {
        Descriptors->GetFrameSet(),
        Descriptors->GetBindlessSet(),
    };
    const uint32_t dynamicOffset = static_cast<uint32_t>(uboAlloc.Offset);
    vkCmdBindDescriptorSets(frame.Cmd, VK_PIPELINE_BIND_POINT_GRAPHICS,
                             PipelineLayout, 0, 2, sets, 1, &dynamicOffset);

    const VkDeviceSize vboOffset = vboAlloc.Offset;
    vkCmdBindVertexBuffers(frame.Cmd, 0, 1, &ringBuffer, &vboOffset);

    vkCmdDraw(frame.Cmd, 6, static_cast<uint32_t>(Pending.size()), 0, 0);

    Pending.clear();
}
