// The .smesh format keeps exactly one version live: a version bump means every
// existing file must regenerate or recook (StaticMeshFormat.h). A committed
// binary mesh silently misses that sweep, and the failure only shows up as a
// runtime load rejection in whatever scene happens to reference it. This walks
// the authored content roots and pins every committed mesh to the live version.

#include <assets/static_mesh/StaticMeshFormat.h>
#include <core/assets/AssetRegistry.h>

#include <gtest/gtest.h>

#include <cstring>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

namespace
{
    // Authored roots only. Cooked artifacts under .cooked/ are build output:
    // untracked, regenerated by the cook, and stale copies in a working tree
    // are not a repository defect.
    const std::vector<std::filesystem::path> AuthoredAssetRoots()
    {
        const std::filesystem::path repo{ SENCHA_REPO_ROOT };
        return {
            repo / "template" / "assets",
            repo / "example" / "CubeDemo" / "assets",
        };
    }

    std::vector<std::filesystem::path> FindCommittedMeshes()
    {
        std::vector<std::filesystem::path> found;
        for (const std::filesystem::path& root : AuthoredAssetRoots())
        {
            std::error_code ec;
            if (!std::filesystem::is_directory(root, ec))
                continue;

            auto iter = std::filesystem::recursive_directory_iterator(root, ec);
            for (const auto& entry : iter)
            {
                if (entry.path().filename() == kCookedCacheDirName)
                {
                    iter.disable_recursion_pending();
                    continue;
                }
                if (entry.is_regular_file(ec) && entry.path().extension() == ".smesh")
                    found.push_back(entry.path());
            }
        }
        return found;
    }
}

TEST(CommittedMeshFormat, AuthoredRootsContainMeshesToCheck)
{
    // Guards the walk itself: a bad root would make every assertion below
    // vacuous.
    EXPECT_FALSE(FindCommittedMeshes().empty());
}

TEST(CommittedMeshFormat, EveryCommittedMeshIsTheLiveFormatVersion)
{
    for (const std::filesystem::path& mesh : FindCommittedMeshes())
    {
        std::ifstream file(mesh, std::ios::binary);
        ASSERT_TRUE(file.is_open()) << mesh.generic_string();

        SmeshFileHeader header{};
        file.read(reinterpret_cast<char*>(&header), sizeof(header));
        ASSERT_EQ(file.gcount(), static_cast<std::streamsize>(sizeof(header)))
            << mesh.generic_string() << ": shorter than a header";

        EXPECT_EQ(std::memcmp(header.Magic, "SMSH", 4), 0)
            << mesh.generic_string() << ": not a .smesh file";
        EXPECT_EQ(header.Version, kSmeshFormatVersion)
            << mesh.generic_string() << ": stale format version, regenerate it";
    }
}
