#pragma once

#include <cstdint>
#include <string_view>

//=============================================================================
// ComponentDefinition
//
// The one place a component's declarative facts are stated: what it is called,
// how it is authored, whether it travels, and whether a tool may remove it.
// Generated by sencha-component-codegen from the annotations on the component's
// own declaration, into a companion header the component header includes -- so
// a definition is visible wherever its component is, and cannot be missing at a
// registration site.
//
// Everything else about a component is behavior and stays handwritten:
// ComponentTraits (lifecycle, owed columns), ComponentStorageTraits (structural
// registration), SceneFieldCodec (how a field type persists). The generator
// neither emits nor reads them.
//
// The consumers do not name this template. TypeSchema, ComponentTypeKey,
// ComponentRemovable and ComponentEditorVisual all project from it, so existing
// code keeps its spelling; a component that still declares one of those by hand
// keeps the handwritten version, because a full specialization outranks the
// constrained partial ones that do the projecting. That is what lets components
// migrate one at a time.
//
// Primary left undefined: only generated specializations carry a definition.
//=============================================================================
template <typename T>
struct ComponentDefinition;

// Every definition states an identity; the rest are optional facts.
template <typename T>
concept HasComponentDefinition = requires { ComponentDefinition<T>::Identity; };

// A component may be authored without being persisted: MovementTuning has a
// schema so the inspector can show it, while a hand-written serializer owns its
// scene form and it declares no chunk.
template <typename T>
concept DefinitionHasSchema = HasComponentDefinition<T>
    && requires { ComponentDefinition<T>::SchemaName; ComponentDefinition<T>::Fields(); };

template <typename T>
concept DefinitionHasSceneChunk = HasComponentDefinition<T>
    && requires { ComponentDefinition<T>::SceneChunk; };

template <typename T>
concept DefinitionIsReplicated = HasComponentDefinition<T>
    && requires { ComponentDefinition<T>::Replicated; };

template <typename T>
concept DefinitionIsPredicted = HasComponentDefinition<T>
    && requires { ComponentDefinition<T>::Predicted; };

// The editor visual travels as the asset path alone rather than as a built
// EditorVisual, so this header does not need EditorVisual.h -- which includes
// this one to do the projecting.
template <typename T>
concept DefinitionHasVisualMesh = HasComponentDefinition<T>
    && requires { ComponentDefinition<T>::VisualMeshAsset; };

//=============================================================================
// Format version
//
// Stamped into every generated companion and checked against this value, so an
// SDK whose generator predates its headers fails at compile naming both
// versions rather than emitting a descriptor the projections cannot read.
// Bump when the emitted shape changes.
//=============================================================================
inline constexpr std::uint32_t kComponentCodegenFormatVersion = 1;
