#!/usr/bin/env python3
"""Cooked scene for the baked-direct Phase 0 spike: a coarse floor plane (few
vertices) beside a fine floor plane (dense), each lit by the identical set of
small accent point lights. Toggling render.baked_direct.spike compares the
per-fragment light loop against per-vertex-interpolated direct light; the
coarse-vs-fine planes show how badly interpolation smears on sparse geometry.

Reads the two plane .smesh assets generated by gen_flat_plane_smesh.py.
Usage: gen_phase0_spike_scene.py <out.cooked.json>
"""

import json
import sys

# Ids are required by the component schema; the dev build resolves the mesh by
# path when the id is absent from the id map, so the plane ids are placeholders.
# The material reuses gray.smat's real cooked id.
COARSE = {"id": "00000000000c0a5e", "path": "asset://levels/phase0_spike/floor_coarse.smesh"}
FINE = {"id": "00000000000f1a5e", "path": "asset://levels/phase0_spike/floor_fine.smesh"}
MATERIAL = {"id": "3654820ec38aab53", "path": "asset://materials/dev/gray.smat"}

PALETTE = [
    [0.05, 0.10, 1.00],   # blue
    [0.99, 0.65, 0.22],   # amber
    [0.10, 0.85, 0.95],   # cyan
]
LIGHT_RANGE = 3.5
LIGHT_INTENSITY = 12.0
LIGHT_Y = 1.3
LIGHT_ZS = [1.0, -3.0, -7.0]   # three lights receding down each plane


def transform(pos, scale=(1, 1, 1)):
    return {"local": {"position": list(pos),
                      "rotation": [0, 0, 0, 1],
                      "scale": list(scale)}}


def plane(mesh, center_x):
    return {"components": {
        "Transform": transform((center_x, 0, -3)),
        "StaticMesh": {
            "mesh": dict(mesh),
            "materials": [dict(MATERIAL)],
            "visible": True,
            "layer_mask": 4294967295,
            "section_mask": 4294967295,
        },
    }}


def lights(center_x, bake):
    ents = []
    for k, z in enumerate(LIGHT_ZS):
        light = {
            "color": PALETTE[k % len(PALETTE)],
            "intensity": LIGHT_INTENSITY,
            "range": LIGHT_RANGE,
            "enabled": True,
        }
        if bake:
            light["bake_contribution"] = bake
        ents.append({"components": {
            "Transform": transform((center_x, LIGHT_Y, z)),
            "PointLight": light,
        }})
    return ents


def main():
    # Optional second arg: bake_contribution for the lights ("direct" to author
    # them baked, so they are excluded from the runtime set).
    if len(sys.argv) not in (2, 3):
        print(__doc__)
        return 1
    bake = sys.argv[2] if len(sys.argv) == 3 else None
    entities = [plane(COARSE, -6.5), plane(FINE, 6.5)]
    entities += lights(-6.5, bake) + lights(6.5, bake)
    scene = {"version": 1, "entities": entities}
    with open(sys.argv[1], "w") as f:
        json.dump(scene, f, indent=1)
    print(f"wrote {sys.argv[1]}: coarse+fine planes, {len(entities) - 2} lights"
          f"{' (baked ' + bake + ')' if bake else ''}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
