name: Export Template Source

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  export-template-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@e8d4307400f9427dba7cb98e488d6ab85f1cec5f

      - name: Upload template source
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: template-source
          path: template/src/TemplateGame.cpp
          if-no-files-found: error
